services:
  portfolio:
    build: .
    container_name: sidharth-portfolio
    restart: always
    ports:
      - "3500:3500"
    volumes:
      - ./messages.json:/usr/src/app/messages.json
    environment:
      - PORT=3500
      - NODE_ENV=production
