services:
  portfolio:
    build: .
    container_name: sidharth-portfolio
    restart: always
    ports:
      - "8601:8601"
    volumes:
      - ./data/messages.json:/usr/src/app/data/messages.json
    environment:
      - PORT=8601
      - NODE_ENV=production
